
const ReturnCode = {
    PAGE_NOT_FUND_CODE: 403,
    PAGE_NOT_FUND_MSG: '页面不存在',
    LOGIN_SUCCEED_CODE: 1,
    LOGIN_SUCCEED_MSG: '登录成功',

    ERROR_LOGIN_UNKNOWN_CODE: -1,
    ERROR_LOGIN_UNKNOWN_MSG: '未知错误',
    ERROR_LOGIN_NOT_USER_CODE: -2,
    ERROR_LOGIN_NOT_USER_MSG: '用户不存在',
    ERROR_LOGIN_WRONG_PWD_CODE: -3,
    ERROR_LOGIN_WRONG_PWD_MSG: '密码错误',
    ERROR_LOGIN_USER_FREEZED_CODE: -4,
    ERROR_LOGIN_USER_FREEZED_MSG: '账号被冻结',

    REGISTER_SUCCEED_CODE: 1,
    REGISTER_SUCCEED_MSG: ''
};

export default ReturnCode;
